### ISSUE TITLE
Top 5 run getters(all seasons)

### ISSUE THREAD

**Issue by sakshamj74** [sakshamj74/IPL-Analysis#1]
Analyze "deliveries.csv" to get the Top 5 run-getters(all seasons) and show the results using some innovative and easy to understand plots.

**Comment by kritikaparmar-programmer** [comment]
@sakshamj74 please assign this issue to me.

**Comment by Pranav25191** [comment]
@sakshamj74 please assisgn this issue to me

**Comment by snehagupta-4** [comment]
May I also work on this issue?
