### ISSUE TITLE
Merging Excel Files

### ISSUE THREAD

**Issue by kavania2002** [sakshamj74/IPL-Analysis#107]
Add all the things about 2020. ( same as we did in old data)
I mean doing same things with the same data.

**Comment by sakshamj74** [comment]
@kavania2002  What I was thinking that if we can merge that data with the existing data and then perform the analysis. What do you think about it?

**Comment by kavania2002** [comment]
Ohkay so like, merging the deliveries and matches of 2020 with the older one right??
I will do it.

**Comment by sakshamj74** [comment]
yeah right.
