### ISSUE TITLE
Stadium Wise Analysis

### ISSUE THREAD

**Issue by AmanSingh0-0** [sakshamj74/IPL-Analysis#13]
Analyze data to get the stadium wise analysis of teams preference regarding batting first or second and plot the result using some innovative and easy to understand plots.

**Comment by Player0109** [comment]
Can I work on this?

**Comment by sakshamj74** [comment]
Ya sure. Go ahead

**Comment by sakshamj74** [comment]
@Player0109 This issue was opened by @AmanSingh0-0. So let him work on it first. You can open a new issue for what you want to analyze.

**Comment by uddeshyatyagi** [comment]
can you assign this issue to me as well?
