### ISSUE TITLE
Best Batsmen Analysis

### ISSUE THREAD

**Issue by Player0109** [sakshamj74/IPL-Analysis#16]
Analyze the performances of some of the best batsmen and show them using some nice plots

**Comment by sakshamj74** [comment]
@Player0109  You can work on this.

**Comment by Player0109** [comment]
![Batsmen Analysis](https://user-images.githubusercontent.com/40686356/101023139-58707c00-3598-11eb-914e-6c4c97c17325.png)

Analysis of David Warner, Virat Kohli and Rohit Sharma.

**Comment by Player0109** [comment]
![Batsmen](https://user-images.githubusercontent.com/40686356/101042672-72638c00-35a3-11eb-9aaf-8b5116c6515e.png)

Detailed Analysis of ['DA Warner', 'V Kohli', 'R Sharma', 'AD Russell', 'HH Pandya', 'RR Pant']
