### ISSUE TITLE
Finding the biggest victories in IPL

### ISSUE THREAD

**Issue by bhanuexcalibur** [sakshamj74/IPL-Analysis#17]
Analysing the data, we need to find the biggest victories while defending a score or chasing a score

**Comment by bhanuexcalibur** [comment]
can you please assign this to me @sakshamj74

**Comment by sakshamj74** [comment]
@bhanuexcalibur Also plot graph of the top 5 highest winning margins by runs.

**Comment by bhanuexcalibur** [comment]
> @bhanuexcalibur Also plot graph of the top 5 highest winning margins by runs.

ohk sure

**Comment by ashwanirathee** [comment]
@sakshamj74 This issue also hasn't been addressed in last 7 days,pls assign this to me.
