### ISSUE TITLE
Death Over Analysis

### ISSUE THREAD

**Issue by Player0109** [sakshamj74/IPL-Analysis#26]
Death overs are the overs b/w 16-20th over.

Do the following tasks:
(1)(a) Batsmen with most runs in death overs in whole IPL.
(1)(b) Batsmen with most runs in death overs batting first in whole IPL.
(1)(c) Batsmen with most runs in death overs batting second in whole IPL.

(2)(a) Batsmen with most runs in death overs in each season.
(2)(b) Batsmen with most runs in death overs batting first in each season.
(2)(c) Batsmen with most runs in death overs batting second in each season.

(3)(a) Batsmen with best StrikeRate in death overs in whole IPL.
(3)(b) Batsmen with best StrikeRate in death overs batting first in whole IPL.
(3)(c) Batsmen with best StrikeRate in death overs batting second in whole IPL.

(4)(a) Batsmen with best StrikeRate in death overs in each season.
(4)(b) Batsmen with best StrikeRate in death overs batting first in each season.
(4)(c) Batsmen with best StrikeRate in death overs batting second in each season.

(5)(a) Bowlers with Most Wickets in death overs in whole IPL.
(5)(b) Bowlers with Most Wickets in death overs bowling first in whole IPL.
(5)(c) Bowlers with Most Wickets in death overs bowling second in whole IPL.

(6)(a) Bowler with most Wickets in death overs in each season.
(6)(b) Bowler with most Wickets in death overs bowling first in each season.
(6)(c) Bowler with most Wickets in death overs bowling second in each season.

(7)(a) Bowlers with Best Economy in death overs in whole IPL.
(7)(b) Bowlers with Best Economy in death overs bowling first in whole IPL.
(7)(c) Bowlers with Best Economy in death overs bowling second in whole IPL.

(8)(a) Bowler with Best Economy in death overs in each season.
(8)(b) Bowler with Best Economy in death overs bowling first in each season.
(8)(c) Bowler with Best Economy in death overs bowling second in each season.

**Comment by sakshamj74** [comment]
@Player0109 You can work on this and make a separate file for this.

**Comment by sakshamj74** [comment]
And don't forget to add one or two lines of comment explaining your approach.

**Comment by ashwanirathee** [comment]
@sakshamj74 Can I work on this??Orignial Assignee hasn't made changes in last 7 days

**Comment by Player0109** [comment]
I am still working on it
I am also working on adding death over team analysis.

**Comment by ashwanirathee** [comment]
@s-ayush2903 @sakshamj74  Is there any rule mentioned in code of conduct regarding the time a issue can be assigned to someone and how long they can work on it before it being reassigned??

**Comment by sakshamj74** [comment]
@ashwani-rathee There is not but you can look for any other issue which is inactive for 7-10 days. I can assign it to you if the other person is not working on it.
