### ISSUE TITLE
Top wicket takers

### ISSUE THREAD

**Issue by sakshamj74** [sakshamj74/IPL-Analysis#3]
Analyze "deliveries.csv" to get the top wicket-takers in IPL History and show the results using some innovative and easy to understand plots.

**Comment by Vrindagupta6828** [comment]
@sakshamj74 please assign this issue to me

**Comment by Vrindagupta6828** [comment]
@sakshamj74 Can you please brief a little what exactly i have to do and how i have to do it?

**Comment by sakshamj74** [comment]
Analyze data and find out bowlers who have taken the most wickets in IPL.

**Comment by Player0109** [comment]
![top_10_wickettakers](https://user-images.githubusercontent.com/40686356/100780016-390a0f80-342f-11eb-921e-f2ed691a9d4d.jpg)

Top 10 wickets takers in the History of IPL.

**Comment by Player0109** [comment]
![top_10_bowlers_score](https://user-images.githubusercontent.com/40686356/100780246-7ff80500-342f-11eb-83b3-50db07f15f09.jpg)

In this, I used SCORE to calculate the top 10 bowlers
SCORE = NUMBER OF WICKETS/NUMBER OF MATCHES PLAYED
and with a minimum qualification of at least 50 wickets.
