### ISSUE TITLE
Graph for matches won with batting first is showing graph for choosing to bat first

### ISSUE THREAD

**Issue by AbhigyanMartin** [sakshamj74/IPL-Analysis#32]
The current Graph shows 100% win for matches won by the team batting first while the data shows a win percentage of 42.8% for the team batting first.

**Comment by AbhigyanMartin** [comment]
If possible please assign this to me.

**Comment by sakshamj74** [comment]
Hey @AbhigyanMartin Which graph are you referring to?
Can you please share an ss of it?

**Comment by AbhigyanMartin** [comment]
@sakshamj74 this is the graph that I am referring to
![Screenshot (93)](https://user-images.githubusercontent.com/10574126/101236753-a355d500-36f9-11eb-8575-3efbb34658e5.png)

If we look at the data for St. George's Park stadium
![Screenshot (94)](https://user-images.githubusercontent.com/10574126/101236755-a4870200-36f9-11eb-90ca-2bb7e7b3b811.png)

We see that 7 out of the 7 teams chose to bat first while only 3 teams won the match batting first.

**Comment by sakshamj74** [comment]
@AbhigyanMartin Nice one!!!
You can work on this.
