### ISSUE TITLE
A plot of most wickets by a team in the very first over.

### ISSUE THREAD

**Issue by kavania2002** [sakshamj74/IPL-Analysis#35]
Actually, I have a very little experience regarding this. But I would like to give more ideas for the analysis.

**Comment by sakshamj74** [comment]
It's Good. You can work on this.

**Comment by sakshamj74** [comment]
@kavania2002  please make a separate file for your analysis. And plot this for each team.

**Comment by kavania2002** [comment]
Ohkay, I will work on it.

**Comment by kavania2002** [comment]
And what about the points regarding raising the issues?

**Comment by kavania2002** [comment]
Thanks for updating the score
