### ISSUE TITLE
Details of All the Super Over Matches

### ISSUE THREAD

**Issue by kavania2002** [sakshamj74/IPL-Analysis#37]
I would like to contribute to it.

**Comment by sakshamj74** [comment]
@kavania2002 You can start!!

**Comment by kavania2002** [comment]
When will the score be updated?

**Comment by sakshamj74** [comment]
@kavania2002  I have already updated your score. Initially, you have one point. I have given you 5 more points.

**Comment by kavania2002** [comment]
But I opened two issues for that 4 points and solved 2 issues so 5 more points.
