### ISSUE TITLE
Analyzing two Teams

### ISSUE THREAD

**Issue by sakshamj74** [sakshamj74/IPL-Analysis#4]
Pick your favorite team and the team you dislike most.
Use "matches.csv" and find who win most matches OR Most Mom awards i OR leading run-scorer OR leading wicket-taker in head to head matches.

**Comment by Halix267** [comment]
@sakshamj74 Please assign me this.

**Comment by anushka17agarwal** [comment]
Hey, I would like to work on this issue. Please assign it to me

**Comment by NEERAJAP2001** [comment]
Looks Interesting!! Is this being worked on? because the favorite team is variable right(person to person)? can I work on this?
I'm asking because it's assigned already and that is stopping me!
@sakshamj74
