### ISSUE TITLE
Top 10 batsman in IPL-history(all seasons)

### ISSUE THREAD

**Issue by Halix267** [sakshamj74/IPL-Analysis#46]

**Comment by Halix267** [comment]
@sakshamj74 I would like to work on it.Can u assign me this

**Comment by sakshamj74** [comment]
@Halix267 You can work on this.

**Comment by sakshamj74** [comment]
@Halix267 Please don't do this.I just checked it is already done

**Comment by Halix267** [comment]
@sakshamj74 I am plotting the total runs scored by the batsmen and the accordingly plotting the curve. The previous issue what u are saying is about top scorer in each season and that is done by me

**Comment by Halix267** [comment]
![Screenshot from 2020-12-08 13-34-00](https://user-images.githubusercontent.com/63572018/101456507-2c6b4700-395a-11eb-93c9-c713c9aa2737.png)

**Comment by Halix267** [comment]
Is this plot is done @sakshamj74 ?
