### ISSUE TITLE
Analysis of teams that have played and won the maximum finals

### ISSUE THREAD

**Issue by Halix267** [sakshamj74/IPL-Analysis#47]
I would like to work on this issue. Can u assign me this

**Comment by Halix267** [comment]
@sakshamj74

**Comment by sakshamj74** [comment]
Do Your analysis on seperate file. @Halix267

**Comment by Halix267** [comment]
ok @sakshamj74 . I have also opened other issues can u plzz check that.

**Comment by Halix267** [comment]
Also will i get 2 points for generating the issue ?
