### ISSUE TITLE
Winning Toss == Winning Match??

### ISSUE THREAD

**Issue by Vrindagupta6828** [sakshamj74/IPL-Analysis#49]
We can analyze that did the team that won the toss in a match also won the match?

**Comment by spursbyte** [comment]
Yes i think i can help with some inshights. And i like study and analyse corelations within data.

**Comment by Vrindagupta6828** [comment]
@sakshamj74 Do i have to work on this or not?

**Comment by ashwanirathee** [comment]
@sakshamj74  Is this being worked upon??

**Comment by Vrindagupta6828** [comment]
Yes i will be working on it

**Comment by Vrindagupta6828** [comment]
@sakshamj74 ???

**Comment by sakshamj74** [comment]
@Vrindagupta6828  Are you working on it?

**Comment by Vrindagupta6828** [comment]
That is what i am asking should i start working on it..and also please give me points for raising these 2 issues

**Comment by sakshamj74** [comment]
@Vrindagupta6828 You can work on it.

**Comment by Vrindagupta6828** [comment]
and also please give me points for raising these 2 issues
