### ISSUE TITLE
Top 5 all Rounders

### ISSUE THREAD

**Issue by sakshamj74** [sakshamj74/IPL-Analysis#5]
Analyze "deliveries.csv" to get top all-rounders in IPL history based on wickets taken and runs scored and visualize the results.

**Comment by Vrindagupta6828** [comment]
@sakshamj74 Please assign me this.

**Comment by Vrindagupta6828** [comment]
@sakshamj74 Can you please brief a little what exactly i have to do and how i have to do it?

**Comment by sakshamj74** [comment]
In the data pick up the players with the most (wickets and runs). You can decide the weightage which should be given to runs scored and wickets taken to pick the best top 5 all-rounders.

**Comment by Player0109** [comment]
![All_rounder](https://user-images.githubusercontent.com/40686356/100773199-8c2b9480-3426-11eb-804f-e8835ef271cb.jpg)

In this, I have used a minimum qualification of 1000 Runs and 40 Wickets to qualify as an allrounder.
And to calculate the score I have used the below formula:
                                              SCORE = RUNS + 25*WICKETS
And Thus calculated the TOP 5 All Rounders based on this score.

**Comment by sakshamj74** [comment]
Awesome!!!
Actually, I have already assigned this to @Vrindagupta6828.
@Player0109 let's wait for a day or two for her. If she doesn't do Please make a PR I will review and merge your code. Till then you can work on some other aspect and Please raise a issue regarding that before you start work.

**Comment by Player0109** [comment]
![All_rounder_last_5years](https://user-images.githubusercontent.com/40686356/100775420-46bc9680-3429-11eb-9429-bee84958574b.jpg)

I also Did the same analysis for the last 5 years.
Minimum Runs Requirement = 500 runs
Minimum Wickets requirement = 20 wickets
SCORE = RUNS + 25*WICKETS
And thus used this SCORE to find the TOP 5 All Rounder in Last 5 years.

**Comment by sakshamj74** [comment]
@Player0109 create an issue for that and then make a pr. This process is important to get points otherwise your contributions might get missed while scoring.

**Comment by Player0109** [comment]
Ok! Thanks for Telling Me!

**Comment by Player0109** [comment]
Do I have to make changes in the deliveries.ipynb file or create a new file?

**Comment by sakshamj74** [comment]
@Player0109  Make changes in deliveries.ipynb

**Comment by sakshamj74** [comment]
Hey, @Vrindagupta6828. Are you working on this? How long it will take?

**Comment by Vrindagupta6828** [comment]
Yes @sakshamj74 i am working on it.... Give me a day or two

**Comment by Vrindagupta6828** [comment]
@sakshamj74 Please first merge my pr #19 then only i will be able to raise this pr as I think else there will be conflicts in the deliveries.ipynb file.
