### ISSUE TITLE
Which team won the most tosses

### ISSUE THREAD

**Issue by Vrindagupta6828** [sakshamj74/IPL-Analysis#50]

**Comment by kavania2002** [comment]
Are you working on this??

**Comment by Vrindagupta6828** [comment]
@kavania2002 yes

**Comment by sakshamj74** [comment]
@Vrindagupta6828 Also, make a plot with that showing the overall win percentage of the team relative to toss winning.

**Comment by Vrindagupta6828** [comment]
@sakshamj74  Ok sure. And please give me the points for raising the issue.
