### ISSUE TITLE
HIghest Team Total each season.

### ISSUE THREAD

**Issue by sakshamj74** [sakshamj74/IPL-Analysis#6]
Analyze data to get the Highest team score (every season) and plot the result using some innovative and easy to understand plots.

**Comment by Halix267** [comment]
@sakshamj74 Please assign me this.

**Comment by Player0109** [comment]
![Highest Team Total each season](https://user-images.githubusercontent.com/40686356/100752503-b2ddd100-340e-11eb-9867-f8b42b3164c3.jpg)

**Comment by Player0109** [comment]
Does this suffice as answer to this?

**Comment by Halix267** [comment]
Hey @Player0109 .Actually this issue is assigned to me , So i m working on this  is issue ,if u are searching for an issue to work on , you can create one and ask for the same :)

**Comment by Player0109** [comment]
Sorry.

**Comment by Halix267** [comment]
Are dont be sorry. You can ask for issue ,you can plot many different relation.
