### ISSUE TITLE
Team wining by 10 wickets

### ISSUE THREAD

**Issue by kavania2002** [sakshamj74/IPL-Analysis#71]
Plot of team name and number of times they won by 10 wickets

**Comment by sakshamj74** [comment]
Hey, @kavania2002 I think some work related to this has been done, Please check once. If not done you can work on this.

**Comment by kavania2002** [comment]
I just saw, there is only number of matches won by 0,1,2,.....10 wickets.
Should I work upon this?

**Comment by sakshamj74** [comment]
@kavania2002 It's fine then. You can do this analysis in continuation of that analysis.
