### ISSUE TITLE
Strike rate of Kieron Pollard in 16-20 overs

### ISSUE THREAD

**Issue by kavania2002** [sakshamj74/IPL-Analysis#75]
Might include other top players having highest strike rate.
Plot of player name and it's strike rate.

**Comment by sakshamj74** [comment]
@kavania2002  
Also, do an analysis of the top 5 strikers. Like what percentage of runs they score in 4's and 6's, their averages, etc.

**Comment by kavania2002** [comment]
Ohh yeah sure.
But then wouldn't it become Intermediate Problem

**Comment by kavania2002** [comment]
Regarding the 4's and 6's I would have to make another file.

**Comment by kavania2002** [comment]
Thanks for updating my score.
