### ISSUE TITLE
Most Wide Thrown by a Bowler

### ISSUE THREAD

**Issue by kavania2002** [sakshamj74/IPL-Analysis#77]
Plot of Player Name and number of wides thrown.

**Comment by SudhanshuBlaze** [comment]
Hi, I am a newbie. I am looking forward for my first Open Source contribution. Please assign this to me.

**Comment by kavania2002** [comment]
Sorry @SudhanshuBlaze I am already working upon this.

**Comment by kavania2002** [comment]
Thanks for updating the score.
