### ISSUE TITLE
Most No-Balls by the bowler

### ISSUE THREAD

**Issue by kavania2002** [sakshamj74/IPL-Analysis#78]
Plot of bowler name and number of no-balls thrown.

**Comment by SudhanshuBlaze** [comment]
Hi, I am a newbie. I am looking forward for my first Open Source contribution. Please assign this to me.

**Comment by kavania2002** [comment]
See if you really want to learn then you can work on this.
But the mentor will decide about this. I don't any issue.
@sakshamj74 Assign this to @SudhanshuBlaze

**Comment by sakshamj74** [comment]
@SudhanshuBlaze You can work on it. And try to analyze more of it like how many times the boundary is scored etc. or any other thing you think seems interesting . This way you will learn a lot  Make a separate file for your analysis.

**Comment by SudhanshuBlaze** [comment]
@sakshamj74 thank you. although I'm a beginner but will try.

**Comment by kavania2002** [comment]
Don't worry. I am also a beginner. I started my first open source contribution from here only. I am first year student.

**Comment by SudhanshuBlaze** [comment]
@kavania2002  Wow that's Amazing!!!!.

**Comment by SudhanshuBlaze** [comment]
@sakshamj74 I have done the assigned task and have created a pull request please review and merge it.
