### ISSUE TITLE
Visualization of no. of matches played in each city

### ISSUE THREAD

**Issue by uddeshyatyagi** [sakshamj74/IPL-Analysis#95]
Visualizing the no. of matches that have been hosted by different ipl cities in all the seasons

**Comment by sakshamj74** [comment]
@uddeshyatyagi Have u checked the same task is not done before?

**Comment by uddeshyatyagi** [comment]
It was done in tabular form,i have now visualized it by plotting the graph
of the same,so that user are better able to understand
